name: Report flaky test
description: Finds flaky tests and uploads reports

runs:
  using: composite
  steps:
    - name: Install xmllint tool
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install xmlstarlet
    - id: setup-env
      name: Setup Env Vars
      run: |
    - id: flaky-tests
      name: Find flaky tests
      #if: github.repository == 'infinispan/infinispan'
      shell: bash
      run: |
        PR="${{ github.event.number }}"
        if [ "$PR" != "" ]; then
          shopt -s nullglob globstar
          FLAKY_TEST_GLOB="**/target/*-reports*/**/TEST-*FLAKY.xml"
          TESTS=(${FLAKY_TEST_GLOB})
          for TEST in "${TESTS[@]}"
          do
            TEST_CLASS=$(xmlstarlet sel --template --value-of '/testsuite/testcase/@classname' ${TEST})
            TEST_NAME=$(xmlstarlet sel --template --value-of '/testsuite/testcase/@name' ${TEST})
            TEST_NAME=${TEST_NAME% (Flaky Test)}
            TEST_NAME=${TEST_NAME%%[*}
            TEST_NAME_NO_PARAMS=${TEST_NAME%%\\*}
            FLAKES_PR_COMMENT="   - $FLAKES_PR_COMMENT""\n""$TEST_CLASS#$TEST_NAME_NO_PARAM"
          done
          if [ "$FLAKES_PR_COMMENT" != "" ]; then
            FLAKES_PR_COMMENT="__FLAKY TESTS__\n"$FLAKES_PR_COMMENT"
            pr_url=https://github.com/${{ github.repository }}/pull/$PR
            printf "__FLAKY TESTS__\n\n%s" "$FLAKES_PR_COMMENT" | gh pr comment $pr_url -F -
          fi
        fi
