name: CI Pull Request Open
on:
  pull_request:
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java and Maven
        uses: s4u/setup-maven-action@1.13.0
        with:
          java-version: 21
          maven-version: 3.9.6
      - name: Build with Maven
        run: mvn clean install -B -e -DskipTests -Pnative
