name: CI Pull Request Open
on:
  pull_request:
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java and Maven
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: 21
          maven-version: 3.9.6
      - name: Build with Maven
        run: mvn -s maven-settings.xml clean install -B -e -DskipTests -Pnative
      - name: Test with Maven
        run: > 
          mvn verify -s maven-settings.xml -B -e -DrerunFailingTestsCount=2
                     -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative
