name: PR to Jira
on:
   workflow_run:
     workflows: [CI Pull Request Open]
     types: [completed]
jobs:
   download:
      runs-on: ubuntu-latest
      steps:
        - name: 'Download artifact'
          uses: actions/github-script@v7
          with:
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: context.payload.workflow_run.id,
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "flaky-test-report"
              })[0];
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/flaky-test-report.zip`, Buffer.from(download.data));
        - name: 'Unzip artifact'
          run: unzip flaky-test-report.zip
        - name: 'Create Jira'
          env:
            TOKEN: ${{ secrets.JIRA_API_TOKEN }}
            RUNNER_DEBUG: 1
            FLAKY_TEST_GLOB: "**/target/*-reports*/**/TEST-*FLAKY.xml"
            PROJECT_KEY: "ISPN"
            TYPE: "Bug"
            JENKINS_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow.id }}"
            TARGET_BRANCH: ${{ github.base_ref }}
          run: bin/jira/track_flaky_tests.sh
