name: CI Pull Request Open
on:
  pull_request:
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: maven
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Build with Maven
        run: mvn clean install -B -e -DskipTests -Pnative
