name: CI Pull Request Open
on:
  pull_request:
jobs:
  ci-build-test-pr:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx1500m -XX:+HeapDumpOnOutOfMemoryError"
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle
          cache: maven
      - run: mvn --version
      - run: >
            mvn -s maven-settings.xml clean install -DskipTests
            -pl :infinispan-component-annotations,:infinispan-logging-annotations,:infinispan-checkstyle,commons,:infinispan-defaults-maven-plugin,:infinispan-logging-processor,:infinispan-commons-spi,:infinispan-component-processor,:infinispan-commons-test,:infinispan-api,:infinispan-commons
      - name: Test with Maven
        run: >
            mvn -s maven-settings.xml verify -B -e -DrerunFailingTestsCount=2
            -Dmaven.test.failure.ignore=true -Dansi.strip=true
            -pl :infinispan-component-annotations,:infinispan-logging-annotations,:infinispan-checkstyle,commons,:infinispan-defaults-maven-plugin,:infinispan-logging-processor,:infinispan-commons-spi,:infinispan-component-processor,:infinispan-commons-test,:infinispan-api,:infinispan-commons
# Create artifact with branch name and surefile flaky test report
      - name: Check flaky report existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "**/target/*-reports*/**/TEST-*FLAKY.xml"
      - name: Archive base_ref
        if: (success() || failure()) && steps.check_files.outputs.files_exists == 'true'
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
        run: echo -n $TARGET_BRANCH > target-branch.txt
      - name: Archive flaky test report
        if: (success() || failure()) && steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: flaky-test-report
          path: |
            **/target/*-reports*/**/TEST-*FLAKY.xml
            target-branch.txt